a = Array.new
a << ["Afghanistan","AF"]
a << ["Albania","AL"]
a << ["Algeria","DZ"]
a << ["American Samoa","AS"]
a << ["Andorra","AD"]
a << ["Angola","AO"]
a << ["Anguilla","AI"]
a << ["Antigua and Barbuda","AG"]
a << ["Argentina","AR"]
a << ["Armenia","AM"]
a << ["Aruba","AW"]
a << ["Australia","AU"]
a << ["Austria","AT"]
a << ["Azerbaijan","AZ"]
a << ["Azores","PT"]
a << ["Bahamas","BS"]
a << ["Bahrain","BH"]
a << ["Bangladesh","BD"]
a << ["Barbados","BB"]
a << ["Belarus","BY"]
a << ["Belgium","BE"]
a << ["Belize","BZ"]
a << ["Benin","BJ"]
a << ["Bermuda","BM"]
a << ["Bhutan","BT"]
a << ["Bolivia","BO"]
a << ["Bonaire","AN"]
a << ["Bosnia","BA"]
a << ["Botswana","BW"]
a << ["Brazil","BR"]
a << ["British Virgin Islands","VG"]
a << ["Brunei","BN"]
a << ["Bulgaria","BG"]
a << ["Burkina Faso","BF"]
a << ["Burundi","BI"]
a << ["Cambodia","KH"]
a << ["Cameroon","CM"]
a << ["Canada","CA"]
a << ["Canary Islands","ES"]
a << ["Cape Verde Island","CV"]
a << ["Cayman Islands","KY"]
a << ["Central African Republic","CF"]
a << ["Chad","TD"]
a << ["Chile","CL"]
a << ["China, People’s Republic of","CN"]
a << ["Colombia","CO"]
a << ["Comoros","KM"]
a << ["Congo","CG"]
a << ["Congo, The Democratic Republic of","CD"]
a << ["Cook Islands","CK"]
a << ["Costa Rica","CR"]
a << ["Croatia","HR"]
a << ["Curacao","AN"]
a << ["Cyprus","CY"]
a << ["Czech Republic","CZ"]
a << ["Denmark","DK"]
a << ["Djibouti","DJ"]
a << ["Dominica","DM"]
a << ["Dominican Republic","DO"]
a << ["East Timor","TL"]
a << ["Ecuador","EC"]
a << ["Egypt","EG"]
a << ["El Salvador","SV"]
a << ["England","GB"]
a << ["Equatorial Guinea","GQ"]
a << ["Eritrea","ER"]
a << ["Estonia","EE"]
a << ["Ethiopia","ET"]
a << ["Europe","EP"]
a << ["Faeroe Islands","FO"]
a << ["Fiji","FJ"]
a << ["Finland","FI"]
a << ["France","FR"]
a << ["French Guiana","GF"]
a << ["French Polynesia","PF"]
a << ["Gabon","GA"]
a << ["Gambia","GM"]
a << ["Georgia","GE"]
a << ["Germany","DE"]
a << ["Ghana","GH"]
a << ["Gibraltar","GI"]
a << ["Greece","GR"]
a << ["Greenland","GL"]
a << ["Grenada","GD"]
a << ["Guadeloupe","GP"]
a << ["Guam","GU"]
a << ["Guatemala","GT"]
a << ["Guernsey","GG"]
a << ["Guinea","GN"]
a << ["Guinea-Bissau","GW"]
a << ["Guyana","GY"]
a << ["Haiti","HT"]
a << ["Holland","NL"]
a << ["Honduras","HN"]
a << ["Hong Kong","HK"]
a << ["Hungary","HU"]
a << ["Iceland","IS"]
a << ["India","IN"]
a << ["Indonesia","ID"]
a << ["Iraq","IQ"]
a << ["Ireland, Republic of","IE"]
a << ["Israel","IL"]
a << ["Italy","IT"]
a << ["Ivory Coast","CI"]
a << ["Jamaica","JM"]
a << ["Japan","JP"]
a << ["Jersey","JE"]
a << ["Jordan","JO"]
a << ["Kazakhstan","KZ"]
a << ["Kenya","KE"]
a << ["Kiribati","KI"]
a << ["Korea, South","KR"]
a << ["Kosrae","FM"]
a << ["Kuwait","KW"]
a << ["Kyrgyzstan","KG"]
a << ["Laos","LA"]
a << ["Latvia","LV"]
a << ["Lebanon","LB"]
a << ["Lesotho","LS"]
a << ["Liberia","LR"]
a << ["Libya","LY"]
a << ["Liechtenstein","LI"]
a << ["Lithuania","LT"]
a << ["Luxembourg","LU"]
a << ["Macau","MO"]
a << ["Macedonia (FYROM)","MK"]
a << ["Madagascar","MG"]
a << ["Madeira","PT"]
a << ["Malawi","MW"]
a << ["Malaysia","MY"]
a << ["Maldives","MV"]
a << ["Mali","ML"]
a << ["Malta","MT"]
a << ["Marshall Islands","MH"]
a << ["Martinique","MQ"]
a << ["Mauritania","MR"]
a << ["Mauritius","MU"]
a << ["Mayotte","YT"]
a << ["Mexico","MX"]
a << ["Micronesia, Federated States of","FM"]
a << ["Moldova","MD"]
a << ["Monaco","MC"]
a << ["Mongolia","MN"]
a << ["Montenegro","ME"]
a << ["Montserrat","MS"]
a << ["Morocco","MA"]
a << ["Mozambique","MZ"]
a << ["Namibia","NA"]
a << ["Nepal","NP"]
a << ["Netherlands","NL"]
a << ["Netherlands Antilles","AN"]
a << ["New Caledonia","NC"]
a << ["New Zealand","NZ"]
a << ["Nicaragua","NI"]
a << ["Niger","NE"]
a << ["Nigeria","NG"]
a << ["Norfolk Island","NF"]
a << ["Northern Ireland","GB"]
a << ["Northern Mariana Islands","MP"]
a << ["Norway","NO"]
a << ["Oman","OM"]
a << ["Pakistan","PK"]
a << ["Palau","PW"]
a << ["Panama","PA"]
a << ["Papua New Guinea","PG"]
a << ["Paraguay","PY"]
a << ["Peru","PE"]
a << ["Philippines","PH"]
a << ["Poland","PL"]
a << ["Ponape","FM"]
a << ["Portugal","PT"]
a << ["Puerto Rico","PR"]
a << ["Qatar","QA"]
a << ["Reunion","RE"]
a << ["Romania","RO"]
a << ["Rota","MP"]
a << ["Russia","RU"]
a << ["Rwanda","RW"]
a << ["Saba","AN"]
a << ["Saipan","MP"]
a << ["Samoa","WS"]
a << ["San Marino","SM"]
a << ["Saudi Arabia","SA"]
a << ["Scotland","GB"]
a << ["Senegal","SN"]
a << ["Serbia","RS"]
a << ["Seychelles","SC"]
a << ["Sierra Leone","SL"]
a << ["Singapore","SG"]
a << ["Slovakia","SK"]
a << ["Slovenia","SI"]
a << ["Solomon Islands","SB"]
a << ["South Africa","ZA"]
a << ["Spain","ES"]
a << ["Sri Lanka","LK"]
a << ["St. Barthelemy","GP"]
a << ["St. Christopher","KN"]
a << ["St. Croix","VI"]
a << ["St. Eustatius","AN"]
a << ["St. John","VI"]
a << ["St. Kitts and Nevis","KN"]
a << ["St. Lucia","LC"]
a << ["St. Maarten","AN"]
a << ["St. Martin","GP"]
a << ["St. Thomas","VI"]
a << ["St. Vincent and the Grenadines","VC"]
a << ["Suriname","SR"]
a << ["Swaziland","SZ"]
a << ["Sweden","SE"]
a << ["Switzerland","CH"]
a << ["Tahiti","PF"]
a << ["Taiwan","TW"]
a << ["Tajikistan","TJ"]
a << ["Tanzania","TZ"]
a << ["Thailand","TH"]
a << ["Tinian","MP"]
a << ["Togo","TG"]
a << ["Tonga","TO"]
a << ["Tortola","VG"]
a << ["Trinidad and Tobago","TT"]
a << ["Truk","FM"]
a << ["Tunisia","TN"]
a << ["Turkey","TR"]
a << ["Turkmenistan","TM"]
a << ["Turks and Caicos Islands","TC"]
a << ["Tuvalu","TV"]
a << ["U.S. Virgin Islands","VI"]
a << ["Uganda","UG"]
a << ["Ukraine","UA"]
a << ["Union Island","VC"]
a << ["United Arab Emirates","AE"]
a << ["United Kingdom","GB"]
a << ["United States","US"]
a << ["Uruguay","UY"]
a << ["Uzbekistan","UZ"]
a << ["Vanuatu","VU"]
a << ["Vatican City State","VA"]
a << ["Venezuela","VE"]
a << ["Vietnam","VN"]
a << ["Virgin Gorda","VG"]
a << ["Wales","GB"]
a << ["Wallis and Futuna Islands","WF"]
a << ["Yap","FM"]
a << ["Yemen","YE"]
a << ["Zambia","ZM"]
a << ["Zimbabwe","ZW"]

i = 0
a.flatten!
countires = Hash.new
while i < a.size do
  countires["#{a[i]}"] = a[i+1]
  i += 2
end

countires.each do |x, y|
  puts "\"#{x}\" => \"#{y}\","
end

